// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq8eukywtVW7StXHN8Wn0lq9hOGJRvlGk',
    appId: '1:990537535512:web:8259b09e2569591e3c736d',
    messagingSenderId: '990537535512',
    projectId: 'moviedo-b25e8',
    authDomain: 'moviedo-b25e8.firebaseapp.com',
    storageBucket: 'moviedo-b25e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpsF1hnLMeXjrXcD2wpjbtkfPQBiReRhQ',
    appId: '1:990537535512:android:9ceebedfbdc584f63c736d',
    messagingSenderId: '990537535512',
    projectId: 'moviedo-b25e8',
    storageBucket: 'moviedo-b25e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8vDv6WaIhEeIHCFz-R1E0bKcw6CC7QM',
    appId: '1:990537535512:ios:3edf0f9ad8abdf193c736d',
    messagingSenderId: '990537535512',
    projectId: 'moviedo-b25e8',
    storageBucket: 'moviedo-b25e8.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8vDv6WaIhEeIHCFz-R1E0bKcw6CC7QM',
    appId: '1:990537535512:ios:3edf0f9ad8abdf193c736d',
    messagingSenderId: '990537535512',
    projectId: 'moviedo-b25e8',
    storageBucket: 'moviedo-b25e8.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq8eukywtVW7StXHN8Wn0lq9hOGJRvlGk',
    appId: '1:990537535512:web:fb8e21be27e1111b3c736d',
    messagingSenderId: '990537535512',
    projectId: 'moviedo-b25e8',
    authDomain: 'moviedo-b25e8.firebaseapp.com',
    storageBucket: 'moviedo-b25e8.firebasestorage.app',
  );
}
